### ISSUE TITLE
Typed data sources / datasets

### ISSUE THREAD

**Issue by jb-adams** [ga4gh/drs-server#21]
Currently, the `DataSource` class only provides a simple mapping of object Id to file path. While this may be sufficient for local files, this is insufficient for other data store types (e.g. s3). Suggest creating a means by which a `DataSource` interface is subclassed by multiple `DataSource` types, each with their own unique required fields, and methods of resolving paths to objects. For example:

* `file://` - local file data stores need to map object ids to file/directory paths
* `s3://` - s3 bucket data stores must have a specified AWS region, bucket name, directory path, etc.

Properties should be specified by the user/admin in the config file, therefore config loading modules will need to be updated.

Suggest only implementing `DataSource` subclasses for local files and s3 buckets for now.

**Comment by brainstorm** [comment]
IIRC htslib solves this by encoding in some semi-standard way in URLs like so:

https://github.com/samtools/htslib/blob/develop/htslib-s3-plugin.7#L41

If possible I'd like to avoid that and leave the S3 URL as-is, having metadata such as the region out of it.

**Comment by jb-adams** [comment]
the [current feature branch](https://github.com/jb-adams/drs-server/blob/feature/typed-data-sources/src/test/resources/config/test-config-00.yml) proposes that s3-based data sources can be defined by providing `bucket` name, `region`, etc. as distinct fields in the config, ie.

```
s3:
  - idPrefix: S3DemoData
     rootDir: /
     region: us-east-2
     bucket: ga4gh-demo-data
```

@brainstorm does this look more like how you'd want this to be defined?

**Comment by brainstorm** [comment]
Yeah, looks good!
